frase = str(input('Digite uma frase: ')).upper()
frase = frase.strip()
print(f'A letra "A" apareceu {frase.count('A')} vezes na frase.')
print(f'A primeira letra "A" apareceu na posicao {frase.find('A')+1}.')
print(f'A ultima letra "A" apareceu na posicao {frase.rfind('A')+1}.')