import random
import time
while True:
    print('Suas opções:')
    print('[1] PEDRA')
    print('[2] PAPEL')
    print('[3] TESOURA')

    jogada = int(input('Qual é a sua jogada? '))
    computador = random.randint(1,3)

    if jogada == 1 and computador == 3:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Tesoura')
        print('Jogador jogou Pedra')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('JOGADOR VENCE')
        print('')
        print('')
    elif jogada == 1 and computador == 2:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Papel')
        print('Jogador jogou Pedra')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('COMPUTADOR VENCE')
        print('')
        print('')
    elif jogada == 1 and computador == 1:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Pedra')
        print('Jogador jogou Pedra')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('EMPATE')
        print('')
        print('')
    if jogada == 2 and computador == 3:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Tesoura')
        print('Jogador jogou Papel')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('COMPUTADOR VENCE')
        print('')
        print('')
    elif jogada == 2 and computador == 2:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Papel')
        print('Jogador jogou Papel')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('EMPATE')
        print('')
        print('')
    elif jogada == 2 and computador == 1:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Pedra')
        print('Jogador jogou Papel')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('JOGADOR VENCE')
        print('')
        print('')
    if jogada == 3 and computador == 3:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Tesoura')
        print('Jogador jogou Tesoura')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('EMPATE')
        print('')
        print('')
    elif jogada == 3 and computador == 2:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Papel')
        print('Jogador jogou Tesoura')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('JOGADOR VENCE')
        print('')
        print('')
    elif jogada == 3 and computador == 1:
        print('JO')
        time.sleep(0.5)
        print('KEN')
        time.sleep(0.5)
        print('PO!!!')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('Computador jogou Pedra')
        print('Jogador jogou Tesoura')
        print('-=-=-=-=-=-=-=-=-=-=-=')
        print('COMPUTADOR VENCE')
        print('')
        print('')



